# Generated by Django 2.2.24 on 2022-12-19 09:06

from django.db import migrations

def copy_flat_to_apartment(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            Flat.objects.filter(id=flat.id).update(new_building=True)
        else:
            Flat.objects.filter(id=flat.id).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(copy_flat_to_apartment),
    ]


