# Generated by Django 2.2.24 on 2022-12-22 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0004_auto_20221219_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_complaint', models.TextField(verbose_name='Текст жалобы')),
                ('flat', models.ForeignKey(on_delete='Квартира, на которую пожаловались', to='property.Flat')),
                ('user', models.ForeignKey(on_delete='Кто жаловался', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
