# Generated by Django 3.2.16 on 2022-12-26 04:52

from django.db import migrations
import phonenumbers

def normalization_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone):
            Flat.objects.filter(id=flat.id).update(owner_pure_phone=phonenumbers.format_number(phone, phonenumbers.PhoneNumberFormat.E164))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RunPython(normalization_phone_number),
    ]
