# Generated by Django 3.2.16 on 2022-12-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_owner_owner_pure_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flat',
            new_name='flats',
        ),
    ]
