# Generated by Django 3.2.16 on 2022-12-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_rename_flat_owner_flats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_pure_phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Нормализованный номер владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Номер владельца'),
        ),
    ]
