# Generated by Django 3.2.16 on 2022-12-30 18:07

from django.db import migrations

def owner_data_transfer(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    owner_set = Owner.objects.all()

    for flat in flat_set.iterator():
        holder, status = owner_set.get_or_create(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber, owner_pure_phone=flat.owner_pure_phone)
        if status:
            holder.flats.set(flat_set.filter(owner=holder.owner))

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221230_2106'),
    ]

    operations = [
        migrations.RunPython(owner_data_transfer)
    ]
