# Generated by Django 3.2.16 on 2023-01-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20230116_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, null=True, related_name='flats', to='property.Flat', verbose_name='Квартира в собственности'),
        ),
    ]
